server:
    address: 0.0.0.0
    port: 8080

spring:
    profiles:
        active: cloud

---

spring:
    config:
        activate:
            on-profile: test_unitarios
    datasource:
        url: jdbc:h2:mem:test-db
        username: user
        password: pass
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop

---

spring:
    config:
        activate:
            on-profile: funcional
    datasource:
        url: jdbc:postgresql://localhost:5430/cuentabancaria
        username: admin
        password: ejemplo123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update

---

spring:
    config:
        activate:
            on-profile: cloud
    datasource:
        url: jdbc:postgresql://${DB_HOST:host.docker.internal}:${DB_PORT:5430}/${DB_NAME:cuentabancaria}
        username: ${DB_USER:admin}
        password: ${DB_password:ejemplo123}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
