services:
  taller6-cuentabancaria-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cuentabancaria'
      - 'POSTGRES_PASSWORD=ejemplo123'
      - 'POSTGRES_USER=admin'
    ports:
      - '5430:5432'
